# Generated by Django 4.1.6 on 2023-02-14 01:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BucOverflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dweet',
            new_name='Post',
        ),
    ]
