# Generated by Django 3.1.7 on 2023-04-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucOverflow', '0006_auto_20230224_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
