# Generated by Django 3.1.7 on 2023-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BucOverflow', '0007_auto_20230403_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timeElapsed',
            field=models.TextField(default='just now'),
        ),
    ]
